### ISSUE TITLE
As a User, I want to create a question and save it into my question bank. 

### ISSUE THREAD

**Issue by haotianzhu** [rw-moore/SciLO#21]
UC1.1 in https://github.com/rw-moore/SciLO/wiki/Front-End-Release-Planning#release-1
> UC1: Create a quiz.
UC1.1: Create a question in a question bank. document
UC1.1.1: A question has a title (ID, unique).
UC1.1.2: A question has tags of category.
UC1.1.3: A question has a question body including one or more components.
UC1.1.3.1: Standard components can be UC2.2.1.
UC1.1.3.2: Custom template components can be created and saved.
UC.1.1.4: A question has answers and related marks.
UC.1.1.5: A question can have comments for answers and general explanations.
UC.1.1.6: A question can override the grading scheme (default: averaged of every slot).

My suggestion is that separate process of creating a quiz and creating a question.
User is not allowed to create a quiz with new questions.
The user always creates a blank quiz and then link exists questions to the quiz.

**Comment by TianqiCS** [comment]
I agree with it and in fact there should be a short cut to create and add a question directly in the quiz creation, while the created question will be saved in the question bank.
