### ISSUE TITLE
As a user, when I create question, I can add, edit and remove children field and its category

### ISSUE THREAD

**Issue by haotianzhu** [rw-moore/SciLO#22]
![image](https://user-images.githubusercontent.com/17155218/57826477-b93f2600-7760-11e9-8a70-da9012bfc287.png)

**Comment by TianqiCS** [comment]
@haotianzhu Please replace category with tags

**Comment by haotianzhu** [comment]
@TianqiCS  #23
API https://github.com/rw-moore/SciLO/wiki/Tag-API
