### ISSUE TITLE
add Eslint for coding style

### ISSUE THREAD

**Issue by haotianzhu** [rw-moore/SciLO#40]
My suggestion is that we should use Eslint(javascript lint) to define a set of styling rules.
https://eslint.org/

1. add Eslint to react project
2. add Eslint test script to azure-pipeline.yml

**Comment by TianqiCS** [comment]
The eslint is embedded in CreateReactApp which is already set up

**Comment by haotianzhu** [comment]
@TianqiCS  add Eslint test script to azure-pipeline.yml?
