### ISSUE TITLE
Pagination, sorting, filtering 

### ISSUE THREAD

**Issue by TianqiCS** [rw-moore/SciLO#55]
**Is your feature request related to a problem? Please describe.**
`I would like the backend to feed only the information needed`
**Describe the solution you'd like**
`I would like the backend to handle pagination info and sort & filter the results. A.K.A. handling queries`
**Describe alternatives you've considered**

**Additional context**
```
A sample query could be:
- GET /api/questions?results=10&page=1&sortField=responses&sortOrder=ascend

**Comment by wooloba** [comment]
` GET /api/questions?quiz=[1,2,3]&author=1&tags=[1,2,3]&results=10&page=1&sort=responses&order=ASC`
